repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: "v1.62.3"
    hooks:
      - id: terraform_validate
      - id: terraform_fmt
      - id: terraform_tflint
      - id: terraform_tfsec
        args:
          - --args=--concise-output
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.16.0"
    hooks:
      - id: terraform-docs-go
        args: ["."]
