formatter: markdown table

version: ">= 0.16.0"

sections:
  show-all: true

recursive:
  enabled: true

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true

sort:
  enabled: true
  by: name

output:
  file: README.md
  mode: inject
